package Teste;

import ClassesBasicas.AparelhoDeSom;
import ClassesBasicas.CD;
import ClassesBasicas.CDPlayer;
import ClassesBasicas.Musica;
import ClassesBasicas.USBPlayer;

public class Teste {
public static void main(String[] args) {
	AparelhoDeSom XYZ = new AparelhoDeSom("Sony",60);
	XYZ.ligar(XYZ);
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	CD lh = new CD();
	lh.setNomeDoArtista("Los Hermanos");
	lh.setNomeDoAlbum("Bloco do eu sozinho");
	lh.setAno(2001);
	Musica m1 = new Musica("Todo carnaval tem seu fim","Marcelo Camelo","Los Hermanos",252);
	lh.setMusicas(m1);
	Musica m2 = new Musica("A flor","Rodrigo Amarante","Los Hermanos",210);
	lh.setMusicas(m2);
	Musica m3 = new Musica("Retrato Pra Iaiá","Marcelo Camelo","Los Hermanos",282);
	lh.setMusicas(m3);
	Musica m4 = new Musica("Assim será","Marcelo Camelo","Los Hermanos",194);
	m4.setTempo(194);
	lh.setMusicas(m4);
	Musica m5 = new Musica("Casa pré-fabricada","Marcelo Camelo","Los Hermanos",245);
	lh.setMusicas(m5);
	XYZ.setControleDeFuncao("CD");
	XYZ.alterarFuncao();
	CDPlayer cdplayer = new CDPlayer();
	cdplayer.colocarCD(lh);
	cdplayer.play(m1);
	cdplayer.avancarMusica();
	cdplayer.avancarMusica();
	cdplayer.stop();
	cdplayer.tirarCD();
	XYZ.setControleDeFuncao("Radio");
	XYZ.alterarFuncao();
	XYZ.diminuirVolume();
	XYZ.diminuirVolume();
	XYZ.setControleDeFuncao("USB");
	XYZ.alterarFuncao();
	Musica m6 = new Musica("Pais e filhos","Renato Russo","Legião Urbana",330);
	USBPlayer up = new USBPlayer();
	up.setMusicas(m6);
	Musica m7 = new Musica("All you need is love","John Lennon","The Beatles",212);
	up.setMusicas(m7);
	Musica m8 = new Musica("A flor","Rodrigo Amarante","Rodrigo Amarante",210);
	up.setMusicas(m8);
	Musica m9 = new Musica("Construção","Chico Buarque","Chico Buarque",280);
	up.setMusicas(m9);
	up.play(m6);
	up.avancarMusica();
	up.avancarMusica();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	XYZ.aumentarVolume();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	up.avancarMusica();
	XYZ.desligar(XYZ);
}
}
